export const trips = [
	{
		id: `1`,
		title:`Coolum Beach`,
		description:`Sunshine Coast Surfing, Coolum Beach`,
		icon: `localify`,
		image: `/trips/sunshine_coast_surfing/sunshine_coast_surfing.jpg`,
		time: Date.now(),
		flag: `/svg/flags/au.svg`,
	},
	{
		id: `2`,
		title:`Camino de Santiago`,
		icon: `localify`,
		image: `/jpg/contemplative-reptile.jpg`,
		time: 1622295172675,
		flag: `/svg/flags/es.svg`,
	},
	{
		id: `3`,
		title:`Short`,
		icon: `localify`,
		image: `/jpg/contemplative-reptile.jpg`,
		time: 1622195172675,
		flag: `/svg/flags/az.svg`,
	},
	{
		id: `4`,
		title:`Short`,
		icon: `localify`,
		image: `/jpg/contemplative-reptile.jpg`,
		time: 1622195172675,
		flag: `/svg/flags/az.svg`,
	},
]